# Generated by Django 3.0.3 on 2020-04-03 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goats', '0009_auto_20200402_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goat',
            name='owner',
        ),
        migrations.CreateModel(
            name='GoatToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goats.Goat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
