# Generated by Django 3.0.3 on 2020-04-03 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goats', '0010_auto_20200403_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goattouser',
            name='goat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goats.Goat'),
        ),
        migrations.AlterField(
            model_name='goattouser',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
