# Generated by Django 3.0.3 on 2020-04-16 10:58

from django.db import migrations, models
import goats.models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0011_auto_20200403_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='cold_protection',
            field=models.IntegerField(default=goats.models.random_int),
        ),
        migrations.AddField(
            model_name='goat',
            name='is_inside',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
