# Generated by Django 3.0.3 on 2020-04-03 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('lon', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDataHourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('temp', models.IntegerField(default=0)),
                ('feels_like', models.IntegerField(default=0)),
                ('weather_str', models.CharField(max_length=100)),
                ('wind', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weather_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.WeatherData')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
