# Generated by Django 3.0.3 on 2020-04-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiapp', '0002_auto_20200403_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('lon', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='weatherdatahourly',
            name='weather_data',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.AddField(
            model_name='weatherdatahourly',
            name='geo_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.GeoData'),
        ),
    ]
