# Generated by Django 3.0.3 on 2020-04-16 14:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20200403_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='country_t',
            field=django_countries.fields.CountryField(default='FI', max_length=2),
        ),
    ]
