# Generated by Django 3.0.3 on 2020-04-16 14:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_geodata_country_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='country_t',
        ),
        migrations.AlterField(
            model_name='geodata',
            name='country',
            field=django_countries.fields.CountryField(default='FI', max_length=2),
        ),
    ]
