# Generated by Django 3.0.3 on 2020-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20200416_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdatahourly',
            name='icon',
            field=models.CharField(default='10d', max_length=3),
        ),
    ]
