# Generated by Django 3.0.3 on 2020-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_weatherdatahourly_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdatahourly',
            name='date',
            field=models.CharField(default='16.4.2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdatahourly',
            name='time',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
